### PR TITLE
Parse and transpile external stylesheets - fixes #78.

### LINKED ISSUE #78: Support styles outside of style tag
Currently using the polyfill with CSS styles only works if the styles are inlined into the `head`:

```html
<style>
  .trigger { view-timeline-name: --trigger; }
  .el { animation-timeline: --trigger; }
</style>
```

If you put those styles in a file like `style.css` and link them with:

```html
<link rel="stylesheet" href="style.css" />
```

The polyfill fails silently because it doesn't consider loaded styles.

Until that's supported, might it be worth adding a `console.warn` that any styles not inlined won't be detected? Happy to open a PR for this.

@jh3y

### PR DESCRIPTION
**Pull request by flackr**
In this implementation, a stylesheet's href is replaced with an object URL to the updated stylesheet href.

### CODE REVIEW

File: src/scroll-timeline-css.js [hunk 1]
```diff
@@ -41,8 +41,26 @@ function initMutationObserver() {
...
+    if (linkElement.type != 'text/css' && linkElement.rel != 'stylesheet' || !linkElement.href) {
+      return;
+    }
+    const url = new URL(linkElement.href, document.baseURI);
+    if (url.origin != location.origin) {
+      // Most likely we won't be able to fetch resources from other origins.
+      return;
+    }
+    fetch(linkElement.getAttribute('href')).then(async (response) => {
+      const result = await response.text();
```
Comment (calinoracation) [inline src/scroll-timeline-css.js:55]: Is it worthwhile to defer transpilation to a new task with a setTimeout to avoid blocking if input or other operations are in progress when the fetch completes?

Comment (flackr) [reply src/scroll-timeline-css.js:55]: I'm happy to put a `setTimeout(transpileFunction, 0)` in until we have a reason that it is necessary to transpile as soon as the request is done if you think this will be important.

**Comment by flackr** [comment]
@calinoracation Does this look good as a first step and we can add the timeout and cross-origin whitelist as extra options? It might also be fine to make requests for all css files even if they might fail CORS.

**Review by calinoracation — APPROVED** [review]
Yeah this looks great. Totally in agreement on follow-up to either have an allow list or simply parse everything option and deal with the errors.

File: src/scroll-timeline-css.js (hunk 1 above)
Comment (calinoracation) [reply src/scroll-timeline-css.js:55]: Yeah not critical here, I think I always try to have a performance outlook and know these requests happen pretty early in the user experience. It might definitely be a premature optimization though.
